#!/bin/python

import sys


n = int(raw_input().strip())
a = map(int,raw_input().strip().split(' '))

if n > 3:
    print 0
elif n ==1:
    print 2
elif n==2:
    print 1
elif n==3:
    a.sort()
    if a[0]+a[1] == a[2]:
        print 1
    else:
        print 0
