#!/bin/python

import sys
import math


t = int(raw_input().strip())

#find at which iteration we reach that time

q=float(t)/3

iteration= int(math.floor(math.log(math.ceil(q),2)))

#now we know at which iteration we are
#print iteration

#sum the time till the current iteration
c=0
for i in xrange(iteration):
    c+=3*2**i
c+=1    

#print c

#at the i iteration, there are 3*2**i cell, starting with 3*2**i and ending with 1
n=3*2**iteration

print n - (t-c)
